camel.beans.moviesDb = #class:org.h2.jdbcx.JdbcDataSource
camel.beans.moviesDb.URL = jdbc:h2:tcp://localhost:9092/movies
camel.beans.moviesDb.user = sa
camel.beans.moviesDb.password =

camel.beans.actorsDb = #class:org.h2.jdbcx.JdbcDataSource
camel.beans.actorsDb.URL = jdbc:h2:tcp://localhost:9093/actors
camel.beans.actorsDb.user = sa
camel.beans.actorsDb.password =